# Generated by Django 4.2.7 on 2023-11-06 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('indiv', 'Individual'), ('grp', 'Group')], default='indiv', max_length=50)),
                ('start_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('max_users', models.IntegerField(default=1)),
                ('recipients', models.ManyToManyField(to='api.recipient')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.software')),
            ],
        ),
    ]
